include/BitBufferWrite.h File Reference
source code of the bitBufferWrite module's public functions, it is used to write bit per bit into a file.
#include <stdio.h>
Classes
struct BitBuffer
buffer structure
Macros
#define MAX_BITS 8
Functions
void initBitBuffer (BitBuffer *bitBuffer)
initializes the buffer.
void writeBit (BitBuffer *bitBuffer, unsigned char bit, FILE *file)
writes a bit into the buffer, if the buffer is full transfers it to the file.
int flushBuffer (BitBuffer *bitBuffer, FILE *file)
Detailed Description
source code of the bitBufferWrite module's public functions, it is used to write bit per bit into a file.
Author
xyannick3 and CarapaceRose
Function Documentation
flushBuffer()
int flushBuffer (BitBuffer * bitBuffer, FILE * file)
Parameters
bitBuffer flushes the remaining bits from the buffer into the file
file
Returns
the amount of bits that have been added to the file.
Referenced by writeQTCFile().
initBitBuffer()
void initBitBuffer (BitBuffer * bitBuffer)
initializes the buffer.
Parameters
bitBuffer a buffer for bits.
Referenced by writeQTCFile().
writeBit()
void writeBit (BitBuffer * bitBuffer, unsigned char bit, FILE * file)
writes a bit into the buffer, if the buffer is full transfers it to the file.
Parameters
bitBuffer the buffer.
bit the bit.
file the output file.
Referenced by encodeQuadTree(), and writeQTCFile().