include/BitBufferRead.h File Reference
source code of the bitbuffer module, it is used to write bit per bit into a file.
#include <stdio.h>
Classes
struct BitReader
the structure of the BitReader
Macros
#define MAX_BITS 8
Functions
void initBitReader (BitReader *bitReader, FILE *file)
initializes the buffer to read from a text file.
int readBit (BitReader *bitReader, unsigned char *bit)
read a single bit.
int readByte (BitReader *bitReader, unsigned char *byte)
read a Byte (8 bits).
int readTwoBits (BitReader *bitReader, unsigned char *value)
read two bits.
Detailed Description
source code of the bitbuffer module, it is used to write bit per bit into a file.
Author
xyannick3 and CarapaceRose
Function Documentation
initBitReader()
void initBitReader (BitReader * bitReader, FILE * file)
initializes the buffer to read from a text file.
Parameters
bitReader the bitReader that's been initialized
file the file to be read.
Referenced by fillQuadTreefromCompress().
readBit()
int readBit (BitReader * bitReader, unsigned char * bit)
read a single bit.
Parameters
bitReader the bitreader.
bit the bit output.
Returns
1 if successful, 0 if EOF.
Referenced by fillQuadTreefromCompress(), handleFourthChild(), readByte(), readTwoBits(), and theNormalWayyyy().
readByte()
int readByte (BitReader * bitReader, unsigned char * byte)
read a Byte (8 bits).
Parameters
bitReader the bitreader.
bit the output.
Returns
1 if successful, 0 if EOF.
References readBit().
Referenced by fillQuadTreefromCompress(), and theNormalWayyyy().
readTwoBits()
int readTwoBits (BitReader * bitReader, unsigned char * value)
read two bits.
Parameters
bitReader the bitreader.
bit the output.
Returns
1 if successful, 0 if EOF.
References readBit().
Referenced by fillQuadTreefromCompress(), handleFourthChild(), and theNormalWayyyy().