src/filtrage.c File Reference
source file of the filtrage module.
#include "../include/filtrage.h"
#include "../include/QuadTree.h"
#include <math.h>
#include <stdio.h>
Functions
double computeVariance (QuadTreeNode *node, QuadTree *tree)
calculate the variance of a specific node.
void computeVars (QuadTree *tree, double *medvar, double *maxvar)
computer the medvar and maxvar of a quadtree.
int filtrageNode (QuadTree *tree, int nodeIndex, double sigma, double alpha)
filtrageNode is a recursive function that filters the nodes of the tree.
void filtrage (QuadTree *tree, double alpha)
function that filter the nodes of the quadtree
Detailed Description
source file of the filtrage module.
source file of the padPGM.h module.
Author
xyannick3 and CarapaceRose
Function Documentation
computeVariance()
double computeVariance (QuadTreeNode * node, QuadTree * tree)
calculate the variance of a specific node.
Parameters
node the node that's studied.
tree the quadtree to have further info on the quadtree.
Returns
variance
Referenced by computeVars(), and filtrageNode().
computeVars()
void computeVars (QuadTree * tree, double * medvar, double * maxvar)
computer the medvar and maxvar of a quadtree.
Parameters
tree the quadtree.
medvar the calculated medvar
maxvar the maximal variance calculated.
References computeVariance().
Referenced by filtrage().
filtrage()
void filtrage (QuadTree * tree, double alpha)
function that filter the nodes of the quadtree
Parameters
tree the quadtree that's to be filtered.
alpha the value that determines how much the quadtree is to be filtered.
References computeVars(), and filtrageNode().
filtrageNode()
int filtrageNode (QuadTree * tree, int nodeIndex, double sigma, double alpha)
filtrageNode is a recursive function that filters the nodes of the tree.
Parameters
tree the quadtree.
nodeIndex the index of the studied node.
sigma the calculated sigma.
alpha the alpha.
References computeVariance(), and filtrageNode().
Referenced by filtrage(), and filtrageNode().