include/QuadTree.h File Reference
prototype of the public functions and structures of the modude Quadtree.
Classes
struct Counter
structure that helps with the counting.
struct QuadTreeNode
structure of the quadtree.
struct QuadTree
Functions
QuadTree * initQuadTree (int depth)
initializes the quadtree
void freeQuadTree (QuadTree *tree)
frees the quadtree tree, pretty straight forward.
void fillQuadTree (QuadTree *tree, unsigned char *pixels, int x, int y, int size, int nodeIndex, int width)
take a pixmap then fills the quadtree as asked.
void printQuadTree (QuadTree *tree)
displays the tree, node by node, used for debugging.
Detailed Description
prototype of the public functions and structures of the modude Quadtree.
Author
xyannick3 and CarapaceRose
Function Documentation
fillQuadTree()
void fillQuadTree (QuadTree * tree, unsigned char * pixels, int x, int y, int size, int nodeIndex, int width)
take a pixmap then fills the quadtree as asked.
Parameters
tree tree to fill.
pixels pixelmap
x must be initialized at 0
y must be initialized at 0
size the width of the image
nodeIndex must be initialized at 0
width the width of the image.
References fillQuadTree().
Referenced by fillQuadTree().
freeQuadTree()
void freeQuadTree (QuadTree * tree)
frees the quadtree tree, pretty straight forward.
Parameters
tree
initQuadTree()
QuadTree * initQuadTree (int depth)
initializes the quadtree
Parameters
depth depth is necessary to allocate the necessary memory.
Returns
QuadTree*
Referenced by readQTC().
printQuadTree()
void printQuadTree (QuadTree * tree)
displays the tree, node by node, used for debugging.
Parameters
tree the tree to display.