src/ReadQTC.c File Reference
source file of the ReadQTC module.
#include "../include/ReadQTC.h"
#include "../include/BitBufferRead.h"
#include "../include/QuadTree.h"
#include <stdio.h>
#include <string.h>
Functions
void fillQuadTreefromCompress (FILE *file, QuadTree *quadtree)
fills the quadtree from the file
int getNodeDepth (int nodeIndex)
a little function to determine the depth of a node by its index.
int isFourthChild (int nodeIndex)
verifies if the node is the fourth child of a tree.
QuadTree * readQTC (const char *filename)
readQTC takes in input the name of a qtc file and returns a quadtree.
void handleUnitaryParent (QuadTree *quadtree, int i)
fills the node i of the quadtree in the case the parent is unitary.
void handleFourthChild (QuadTree *quadtree, int i, BitReader *bitreader)
fills the quadtree in the case the node is the fourth of a branch.
void theNormalWayyyy (QuadTree *quadtree, int i, BitReader *bitReader)
fills the node of a quadtree.
Detailed Description
source file of the ReadQTC module.
Author
xyannick3 and CarapaceRose
Function Documentation
fillQuadTreefromCompress()
void fillQuadTreefromCompress (FILE * file, QuadTree * quadtree)
fills the quadtree from the file
Parameters
file the file
quadtree the quadtree.
References handleFourthChild(), handleUnitaryParent(), initBitReader(), isFourthChild(), readBit(), readByte(), readTwoBits(), and theNormalWayyyy().
Referenced by readQTC().
getNodeDepth()
int getNodeDepth (int nodeIndex)
a little function to determine the depth of a node by its index.
Parameters
nodeIndex the index of a node.
Returns
the depth.
Referenced by handleFourthChild(), handleUnitaryParent(), and theNormalWayyyy().
handleFourthChild()
void handleFourthChild (QuadTree * quadtree, int i, BitReader * bitreader)
fills the quadtree in the case the node is the fourth of a branch.
Parameters
quadtree the quadtree.
i the index
bitreader the bitreader
References getNodeDepth(), readBit(), and readTwoBits().
Referenced by fillQuadTreefromCompress().
handleUnitaryParent()
void handleUnitaryParent (QuadTree * quadtree, int i)
fills the node i of the quadtree in the case the parent is unitary.
Parameters
quadtree the quadtree
i the index of the node.
References getNodeDepth().
Referenced by fillQuadTreefromCompress().
isFourthChild()
int isFourthChild (int nodeIndex)
verifies if the node is the fourth child of a tree.
Parameters
nodeIndex the node of the index studied
Returns
1 if it is, else 0.
Referenced by fillQuadTreefromCompress().
readQTC()
QuadTree * readQTC (const char * filename)
readQTC takes in input the name of a qtc file and returns a quadtree.
Parameters
filename the name of the qtc file.
Returns
a quadtree.
References fillQuadTreefromCompress(), and initQuadTree().
theNormalWayyyy()
void theNormalWayyyy (QuadTree * quadtree, int i, BitReader * bitReader)
fills the node of a quadtree.
Parameters
quadtree the quadtree
i the index
bitreader the bitreader.
References getNodeDepth(), readBit(), readByte(), and readTwoBits().
Referenced by fillQuadTreefromCompress().