src/SegGrid.c File Reference
source file of the SegGrid module.
#include "../include/SegGrid.h"
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
Functions
void fillPixelsSegGrid (unsigned char *pixels, QuadTreeNode *nodes, int nodeIndex, int x, int y, int size, int width)
fills the pixelmap in the goal of displaying a grid of the segmentation.
int writeGridFromQuadTree (QuadTree *tree, const char *filename, int size)
writes the gridPGM file that showcase the grid of the qtc.
Detailed Description
source file of the SegGrid module.
Author
xyannick3 and CarapaceRose
Function Documentation
fillPixelsSegGrid()
void fillPixelsSegGrid (unsigned char * pixels, QuadTreeNode * nodes, int nodeIndex, int x, int y, int size, int width)
fills the pixelmap in the goal of displaying a grid of the segmentation.
Parameters
pixels the pixmap.
nodes the nodes of the quadtree.
nodeIndex the index of the studied node
x the x coordinate of the top left of the segment
y the y coordinate of the top left of the segment.
size the size of the segment.
width the width of the image.
References fillPixelsSegGrid().
Referenced by fillPixelsSegGrid(), and writeGridFromQuadTree().
writeGridFromQuadTree()
int writeGridFromQuadTree (QuadTree * tree, const char * filename, int size)
writes the gridPGM file that showcase the grid of the qtc.
Parameters
tree the quadtree
filename the name of the output file.
size the width of the image.
References fillPixelsSegGrid().