include/writeQTC.h File Reference
prototype of the public functions and structures of the modude writeQuadTree.
#include "QuadTree.h"
#include "BitBufferWrite.h"
Functions
void writeQTCFile (const char *filename, QuadTree *tree, int imageSize, int depth)
write the quadtree into the qtc file.
Detailed Description
prototype of the public functions and structures of the modude writeQuadTree.
Author
xyannick3 and CarapaceRose
Function Documentation
writeQTCFile()
void writeQTCFile (const char * filename, QuadTree * tree, int imageSize, int depth)
write the quadtree into the qtc file.
Parameters
filename the name of the qtc file.
tree the quadtree.
imageSize the width of the image.
depth the depth.
References calculateCompressionRate2(), calculateSize(), encodeQuadTree(), flushBuffer(), initBitBuffer(), and writeBit().