src/writeQTC.c File Reference
source file of the writeQTC module.
#include "../include/writeQTC.h"
#include "../include/BitBufferWrite.h"
#include <time.h>
#include <unistd.h>
Functions
int isFourthChild2 (int nodeIndex)
verifies if the index is the fourth child
void calculateSize (QuadTree *tree, int nodeIndex, long *m, long *e, long *u)
goes through the tree to precalculate the size of the compressed.
void encodeQuadTree (FILE *file, QuadTree *tree, int nodeIndex, BitBuffer *bitBuffer)
recursive function that encodes the quadtree in the output file.
float calculateCompressionRate2 (long originalSize, long compressedSize)
function that calculates the compression rate.
void writeQTCFile (const char *filename, QuadTree *tree, int imageSize, int depth)
write the quadtree into the qtc file.
Detailed Description
source file of the writeQTC module.
Author
xyannick3 and CarapaceRose
Function Documentation
calculateCompressionRate2()
float calculateCompressionRate2 (long originalSize, long compressedSize)
function that calculates the compression rate.
Parameters
originalSize the original Size of the file.
compressedSize the compressed size.
Returns
the rate of compression.
Referenced by writeQTCFile().
calculateSize()
void calculateSize (QuadTree * tree, int nodeIndex, long * m, long * e, long * u)
goes through the tree to precalculate the size of the compressed.
Parameters
tree the quadtree.
nodeIndex the index.
m the number of m that would be written.
e the number of e that would be written.
u the number of u that would be written.
References isFourthChild2().
Referenced by writeQTCFile().
encodeQuadTree()
void encodeQuadTree (FILE * file, QuadTree * tree, int nodeIndex, BitBuffer * bitBuffer)
recursive function that encodes the quadtree in the output file.
Parameters
file the file.
tree the quadtree.
nodeIndex the index.
bitbuffer the bitbuffer.
References isFourthChild2(), and writeBit().
Referenced by writeQTCFile().
isFourthChild2()
int isFourthChild2 (int nodeIndex)
verifies if the index is the fourth child
Parameters
nodeIndex the index
Returns
1 if it's the fourth child, zero otherwise.
Referenced by calculateSize(), and encodeQuadTree().
writeQTCFile()
void writeQTCFile (const char * filename, QuadTree * tree, int imageSize, int depth)
write the quadtree into the qtc file.
Parameters
filename the name of the qtc file.
tree the quadtree.
imageSize the width of the image.
depth the depth.
References calculateCompressionRate2(), calculateSize(), encodeQuadTree(), flushBuffer(), initBitBuffer(), and writeBit().