src/writePGM.c File Reference
source file of the writePGM module.
#include <time.h>
#include <stdio.h>
#include <stdlib.h>
#include "../include/writePGM.h"
#include "../include/QuadTree.h"
Functions
void fillPixels (unsigned char *pixels, QuadTreeNode *nodes, int nodeIndex, int x, int y, int size, int width)
fills the pixmap with the selected node at the said coordinates.
int writePGMFromQuadTree (QuadTree *tree, const char *filename, int size)
write the PGM from the quadtree
Detailed Description
source file of the writePGM module.
Author
xyannick3 and CarapaceRose
Function Documentation
fillPixels()
void fillPixels (unsigned char * pixels, QuadTreeNode * nodes, int nodeIndex, int x, int y, int size, int width)
fills the pixmap with the selected node at the said coordinates.
Parameters
pixels the pixmap.
nodes the node array.
nodeIndex the index of the node.
x the x coordinate of the pixel.
y the y coordinate of the pixel.
size the size of the area.
width the width of the image.
References fillPixels().
Referenced by fillPixels(), and writePGMFromQuadTree().
writePGMFromQuadTree()
int writePGMFromQuadTree (QuadTree * tree, const char * filename, int size)
write the PGM from the quadtree
Parameters
tree the quadtree
filename the name of the pgm file.
size the width of the image.
References fillPixels().